# Generated by Django 3.1.7 on 2021-06-07 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_doctor_latest_diagnosis_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='valid_until',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
