# Generated by Django 3.1.7 on 2021-06-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_auto_20210607_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_latest_diagnosis',
            name='valid_until',
        ),
    ]
