# Generated by Django 3.1.7 on 2021-05-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumbiaAsia_Doctor',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Patient.account')),
                ('id_doctor', models.IntegerField(unique=True)),
                ('department', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=100)),
                ('work_experience', models.TextField()),
                ('doc_overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_latest_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=100)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Patient_ID', models.IntegerField()),
                ('Doctor_ID', models.IntegerField()),
                ('Department', models.CharField(max_length=100)),
                ('Date_of_updation', models.DateField()),
                ('Diagnosis', models.TextField()),
                ('Diagnosis_description', models.TextField()),
                ('Doctor_advice', models.TextField()),
                ('Additional_comments', models.TextField()),
            ],
        ),
    ]
