# Generated by Django 3.1.7 on 2021-05-11 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0003_doctor_assigned_to_patient_doctor_request_patient_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_assigned_to_patient',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_assigned_to_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
