# Generated by Django 3.1.7 on 2021-05-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_auto_20210511_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columbiaasia_doctor',
            name='department',
            field=models.CharField(choices=[('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Cardiology', 'Cardiology'), ('Diagnostic_Medicine', 'Diagnostic Medicine')], max_length=20),
        ),
    ]
