# Generated by Django 3.1.7 on 2021-05-31 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0008_auto_20210531_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_assigned_to_patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_assigned_to_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
