# Generated by Django 3.1.7 on 2021-06-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Become_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution_name', models.CharField(max_length=100)),
                ('Email_ID', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Source_of_Info', models.CharField(max_length=100)),
            ],
        ),
    ]
